const strings = {
  az: {
    wait: 'yüklənir...',
    loginInput: 'Telefon və ya E-mail',
    phone: 'Telefon nömrəsi',
    email: 'E-mail ünvan',
    passwordInput: 'Şifrə',
    passwordRepeatInput: 'Şifrəni təkrar yazın',
    loginBtn: 'Daxil ol',
    signUpBtn: 'Avtobirliyə qoşul',
    or: 'və ya',
    forgot: 'Parolu unudubsan?',
    wrong_email_password: 'Məlumatlar düzgün deyil',
    signup_email_phone: '+994XX-XXX-XX-XX / emin@gmail.com',
    signup_fullname: 'Emin Jafarov',
    signup_fullname_label: 'Ad və soyad',
    signup_submit: 'Qeydiyyatdan keç',
    signup_loginHeader: 'Telefon nömrəsini və ya Email ünvanını ilə daxil ol',
    signup_fullnameHeader: 'Profiliniz üçün ad və soyad mütləqdi',
    signup_passwordHeader: 'Şifrəniz ən azı 6 hərf/rəqəmd-dən ibarət olmalıdı',
    alreadyExist: 'artıq mövcuddur',
    afterSignup: 'Avtobirliyə xoş gəldin',
    getStarted: 'Başla',
    fromGallery: 'Qalereyadan seç',
    fromCamera: 'Şəkilini çək',
    removePhoto: 'Şəkili sil',
    requireAuto: 'Avtonuzu seçin',
    reselectAuto: 'Avtonu deyiş',
    auto: {
      make: 'Marka',
      model: 'Model',
      year: 'Model ili',
      body: 'Ban növü',
      generation: 'Nəsil',
      engineVolume: 'Mühərrikin həcmi',
      enginePower: 'Mühərrikin gücü',
      engineType: 'Yanacaq növü',
      gearbox: 'Sürətlər qutusu',
      drive: 'Ötürücü',
    },
    engineType: {
      Gasoline: 'Benzin',
      Hybrid: 'Hibrid',
      Electro: 'Elektrik',
      Gas: 'Qaz',
      Diesel: 'Dizel',
    },
    gearboxTypes: {
      Sequential: 'Ardıcıl',
      Robotic: 'Robotik',
      Variator: 'Varyator',
      Automatic: 'Avtomatik',
      Manual: 'Mexaniki', 
      'Direct transmission': 'Direkt transmissiya',
      'Robotic dual clutch': 'Robotik ikili klaç',
      'Robotic one clutch': 'Robotik tək klaç',
    },
    driveTypes: {
      FWD: 'Ön',
      RWD: 'Arxa',
      '4WD': 'Tam',
      'Full Time': 'Tam vaxt ötürücü',
      'Part Time': 'Yarım vaxt ötürücü',
    }
  }
};

export default strings;